### ISSUE TITLE
Update needed in the Durian shard

### ISSUE THREAD

**Issue by icepaco** [elbywan/cryomongo#18] opened 2024-11-12 17:47 UTC
I have created a shard that uses cryomongo.
When I link it to my project and then just do

require "myshard" or even require "cryomongo"

then I get this error :

In lib\durian\src\durian\socket\tcp_socket.cr:2:96

 2 | def self.connect(host : String, port : Int32, resolver : Durian::Resolver, connect_timeout : Int | Float? = nil)
                                                                                                  ^--
Error: can't use Int in unions yet, use a more specific type

I got confirmation on this.  I believe the Durian shards needs to be updated (use Number instead of Int). 

Thank you !

**Comment by icepaco** [comment] 2024-11-12 18:38
This fixed the issue for me (currently using shard override)
https://github.com/icepaco/durian.cr

**Comment by elbywan** [comment] 2024-11-13 11:59
Hey, thanks for reporting the issue.

I could not reproduce but Durian is really outdated. I replaced it with [spider-gazelle/dns](https://github.com/spider-gazelle/dns) and released [v0.3.12](https://github.com/elbywan/cryomongo/releases/tag/v0.3.12) which should solve the problem.

**Comment by Blacksmoke16** [comment] 2024-11-13 14:27
`shard.yml` needs it's version updated to match the tag btw ^.

**Comment by elbywan** [comment] 2024-11-13 14:57
> shard.yml needs it's version updated to match the tag btw ^.

Oh right sorry, I committed a bit too quickly :facepalm: 

Things should be allright now

**Closed as completed** 2024-11-21 17:46 UTC
